project:
  type: website
  output-dir: docs

website:
  title: "my_website"
  navbar:
    search: true
    background: primary
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



