project:
  type: website
  output-dir: docs

website:
  title: "my_website"
  navbar:
    search: true
    background: primary
    collapse: true
    left:
      - href: index.qmd
        text: Home
      - about.qmd
  sidebar: 
    contents: auto
    collapse-level: 3
  back-to-top-navigation: true
  page-navigation: true

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    lang: pl



